spring.application.name=qrcode.generator
server.port=8080

app.storage.local.dir=./backend/qrcodes
spring.web.resources.static-locations=file:./qrcodes/

aws.endpoint=${AWS_ENDPOINT:http://minio:9000}
aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:qrcodes}
aws.s3.public-url=${AWS_S3_PUBLIC_URL:http://localhost:9000}
aws.access-key-id=${AWS_ACCESS_KEY_ID:minioadmin}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY:minioadmin}
